DROP TABLE IF EXISTS users;

create table users(
    ID INT(255) AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    USER_ID VARCHAR(255) NOT NULL,
    created_at datetime NOT NULL,
    PRIMARY KEY (ID)
);