server:
  port: 8000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            PostLogger: true
      routes:
        - id: user-service
          uri: http://localhost:30100/
          predicates:
            - Path=/user-service/**
          filters:
            - name: LoggingFilter
              args:
                baseMessage: Spring Cloud Gateway GlobalFilter
                preLogger: true
                PostLogger: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka