version: '3'

networks:
  elk:
    driver: bridge

services:
  # Elastic search 설정
  elasticsearch:
    platform: linux/x86_64
    container_name: elasticsearch
    image: elasticsearch:7.10.1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
    # Elastic search 계정정보
    environment:
      discovery.type: single-node
      xpack.security.enabled: "true"
      xpack.security.transport.ssl.enabled: "true"
      ELASTIC_USERNAME: "elastic"
      ELASTIC_PASSWORD: "qwer1234!"
    networks:
      - elk

  # Logstash 설정
  logstash:
    platform: linux/x86_64
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.10.1
    ports:
      - "5001:5001"
      - "9600:9600"
    volumes:
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    networks:
      - elk

  # Kibana 설정
  kibana:
    platform: linux/x86_64
    container_name: kibana
    image: kibana:7.10.1
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - elk